# Site settings
title: "Stanley"
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: ""

# Address
address:
  - "Some Address 987,"
  - "+34 9054 5455,"
  - "Madrid, Spain."

# Footer
footer:
  address_headline: "My bunker"
  social_links:
    - title: Facebook
      icon: facebook
      url: "#"
    - title: Instagram
      icon: instagram
      url: "#"
  links_headline: "My links"
  links:
    - title: Dribbble
      url: "https://blacktie.co/demo/stanley/#"
    - title: Twitter
      url: "https://blacktie.co/demo/stanley/#"
    - title: Facebook
      url: "https://blacktie.co/demo/stanley/#"
  about_headline: "About Stanley"
  about: "This cute theme was created to showcase your work in a simple way. Use it wisely."

# Build settings
markdown: kramdown
permalink: pretty

# Sass/SCSS
sass:
  sass_dir: _scss
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Add custom collections
collections:
  work:
    output: true

# Set defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"    
      author: "Stanley Stinson"
